#!/bin/bash

set -euo pipefail

[ ! -f include/ddnet_protocol.h ] && exit 1

echo "// THIS FILE IS AUTOGENERATED BY scripts/generate_include.sh" > include/ddnet_protocol.h

# shellcheck disable=2002
cat \
	src/common.h \
	src/errors.h \
	src/token.h \
	src/chunk.h \
	src/packet.h \
	src/packer.h \
	src/huffman.h \
	| grep -vE '(^#include "|^#pragma once)' >> include/ddnet_protocol.h
